### PR TITLE
Final project

### PR DESCRIPTION
**Pull request by hammaazarok**
**This project is made by me @hammaazarok  in collaboration with @rotshidzw .**
Video Documentation - [here](https://www.loom.com/share/c446b49835c14fa7b31f884352904be9)
Live link - [here](https://hammaazarok.github.io/javascript-capstone/)

### CODE REVIEW

**Review by CollinsTatang — CHANGES_REQUESTED** [review]
Hi @hammaazarok, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.

- [ ] Please your app generates an error when running locally, please fix this error and submit it again for re-review.

comment


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by hammaazarok** [comment]
Hi @CollinsTatang  
Thank you for the review.
Even though I don't have this error for now in my side I will redo the setup and see if it will generate this error and then I will start working on solving it .

**Comment by hammaazarok** [comment]
I did clone the repo in a new folder and test everything works fine as you can see in the pictures below.

image
image

**Review by victorokoroji — APPROVED** [review]
Hi @hammaazarok , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CollinsTatang** [comment]
> Hi @CollinsTatang Thank you for the review. Even though I don't have this error for now in my side I will redo the setup and see if it will generate this error and then I will start working on solving it .

Hi @hammaazarok  
I will try to work it out again on my end again

**Pull request merged**
